Allow multiple @Body objects in request methods
sashirestela/cleverclient pull request #12
Opened 2023-11-06 21:24 UTC by didalgolab

2023-11-08 21:07 UTC, sashirestela reviewed
@didalgolab This is more an observation about styling: could you make explicit imports? If you think that is too effort, just comment on it and don't make changes.

2023-11-08 21:16 UTC, sashirestela commented
@didalgolab I've just put all my observations. Please, let me know when you have fixed them.

2023-11-08 21:56 UTC, didalgolab commented
> @didalgolab could you make explicit imports?

@sashirestela Fixed (it's automatic thing in my IDE, not intentional)

2023-11-08 22:14 UTC, sashirestela commented
@didalgolab Are you aware of my three pending revisions about missing unit testing? (just to be sure)

2023-11-08 22:26 UTC, didalgolab commented
Oh, you mean Codecov Report? I wasn't aware it's directed to me. Thx for heads up. I'm on it.

2023-11-08 22:40 UTC, sashirestela commented
I meant this observations:
![image](https://github.com/sashirestela/cleverclient/assets/14045506/49b37ad1-1bf8-48c0-bd6f-5b6e5c7c3d23)

2023-11-08 22:51 UTC, didalgolab commented
@sashirestela I cannot see comments that are "Pending". Please submit you review first.

2023-11-08 23:03 UTC, sashirestela requested changes

2023-11-08 23:28 UTC, didalgolab commented on src/main/java/io/github/sashirestela/cleverclient/util/JsonUtil.java
> +    public static <T> Map<String, Object> objectToMap(T object) {
Done.

2023-11-08 23:28 UTC, didalgolab commented on src/main/java/io/github/sashirestela/cleverclient/util/JsonUtil.java
> +    public static <T> T jsonToObjectStrict(String json, Class<T> clazz) {
Done.

2023-11-08 23:29 UTC, didalgolab commented on src/main/java/io/github/sashirestela/cleverclient/util/ReflectUtil.java
> +        if (object instanceof Map) {
Done.

2023-11-09 00:01 UTC, sashirestela approved these changes

2023-11-09 00:16 UTC, merged